### ISSUE TITLE
HTML HW-Habtamu Abere-CR6

### ISSUE THREAD

**Issue by HabRonan** [ga-wdi-lessons/html-intro#11]
1. 130 HTML elements but we might just use 20 of them 90% of the time.
2. Indentation seemed more important than ever
3. If you write html perfectly you will never need to touch it once you start writing CSS- Sometimes I go back and change the html

Quiz-
Which of the following is the best way to center the text in div?

`<style>div{ text-align:center; }</style>`

Why do we write `<img />` and not `<img></img>`?

-Because Image tag doesn't have any text content

Why is it important to keep semantics (HTML) separate from style (CSS)?
 -Code maintainability (easy to read, easy to make changes)

**Comment by amaseda** [comment]
:+1:

Although with your first quiz question, what exactly do you mean by center? Depending on what the content of your `div` is, you might need more than `text-align: center`...

**Comment by HabRonan** [comment]
It wasn't a question I come up with and answered. These were the quiz questions that are given after finishing the html-intro and I was attempting to answer them from the choices given.

**Comment by amaseda** [comment]
Ah, roger that. Still something worth thinking about though!
