### ISSUE TITLE
HTML Intro HW (Mike)

### ISSUE THREAD

**Issue by ghost** [ga-wdi-lessons/html-intro#15]
Comfort score: 5			
Completeness score: 5

Three things I've learned from this lesson:
1. All special characters have the same form: an ampersand, followed by an abbreviation, followed by a semicolon.
2. Using (Command Option U) on Google Chrome opens the source of the web page.
3. The ampersand and the angle brackets are also special characters.

**Comment by nayana487** [comment]
👍
