### ISSUE TITLE
Nyketha's Intro to HTML HW

### ISSUE THREAD

**Issue by Nykke** [ga-wdi-lessons/html-intro#16]
Level of Completeness: 5
Level of Understanding: 5

Three things I've learned from this lesson are:
1) It is important to name [classes] according to their functions and not by how you want them to look when writing them in HTML.
2) When things are saved to the "cloud" it's actually being saved to a bunch of host computers. 
3) Every browser have their own default stylesheets, that's why it's important to specify things like italics and bold or the browser might default to their own version. Some designers completely eliminate this problem by using a "normalize.css" file.

**Comment by superbuggy** [comment]
nice insights!
