### ISSUE TITLE
HTML HW

### ISSUE THREAD

**Issue by ericanorby** [ga-wdi-lessons/html-intro#19]
HTML comes with built-in special characters. They consist of an ampersand, an abbreviation, and a semicolon.
	
The <head> of HTML contains metadata (data that the user won't actually see in the webpage), while the <body> contains everything that the user will see.
	
Different browsers do not render HTML and CSS the exact same way, so it is important to check and edit your code for browser compatibility.

**Comment by phantomhaircuts** [comment]
👍
