### ISSUE TITLE
Savraj Singh HTML Intro 

### ISSUE THREAD

**Issue by SavrajSingh** [ga-wdi-lessons/html-intro#20]
I learned quite a lot of things that I did not previously know thanks to the high level html introduction. They might seem like small things but I think they were important.

1. The first thing was how the css selectors are chosen. I tend to make to many and I realized that I should make more general classes that are easier for others who will come see my code to understand. 
2. The second thing was the fact that I need to start indenting and making my code more human readable. 
3. The last thing that stood out to me was the fact that different web browsers have different style sheets. This is very important to know and make sure that it is taken into account while coding.

**Comment by amaseda** [comment]
:+1: especially the second one!
