### ISSUE TITLE
Jared Edwards - HTML intro

### ISSUE THREAD

**Issue by jarededwards** [ga-wdi-lessons/html-intro#21]
Web designers often use CSS normalizers to completely remove the effects of the default stylesheet. A popular one is normalize.css.

<dl>: A definition list is like a dictionary representation of things
.
This is called abstraction: taking something super granular and turning it into something easier to grasp. For example, turning digital signals into HTML, or turning HTML into a visual webpage.

**Comment by nayana487** [comment]
👍
