### ISSUE TITLE
HTML-Intro HW (Fiona N)

### ISSUE THREAD

**Issue by nfiona** [ga-wdi-lessons/html-intro#24]
## **Some cool stuff I've learned:** 

- Great site to test _browser compatibility:_   https://www.browserstack.com
 - "most **important** rule of web design: you should never put anything indicative of style in your HTML." ; "_semantic naming:_ naming things according to their function, rather than how you want them to look. "
- Indent. Indent. Indent. --> **Really Important**
- _Special characters_ all have the same form: an ampersand, followed by an abbreviation, followed by a semicolon.
- The alt attribute is required by law  as a result of the Americans With Disabilities act
-   A definition list (dl) is like a dictionary representation of things; good to use for a list of items on a webstore.
- http://w3.validator.org validates HTML
- file://, which is an absolute path saying where to retrieve a file relative your computer.

**Comment by nayana487** [comment]
👍
