### ISSUE TITLE
HTML-Intro HW-Ben Shapiro

### ISSUE THREAD

**Issue by pretorben** [ga-wdi-lessons/html-intro#25]
1. Special characters can be used in HTML with the syntax ‘&trade;’ (replacing trade with the character code).
2. Browsers have built-in style sheets for web pages that don’t have them included.
3. ‘Normalize.css’ can be used similarly to ‘reset.css’ to remove the effects of default stylesheets.

**Comment by superbuggy** [comment]
👍 nice
