### ISSUE TITLE
HW HTML-intro 

### ISSUE THREAD

**Issue by pootsmagoots** [ga-wdi-lessons/html-intro#27]
1.Remember: If you write HTML perfectly, you'll never need to touch it once you start writing CSS.- This to me is a great reminder as to always focus on writing great HTML and then adding some flavor with CSS.

2. semantic naming: naming things according to their function, rather than how you want them to look.- This to me is a very important feature in web development. Not only does this help you read your code but it also helps other developers read and process what you’re trying to convey.

3. I really agree with the idea of Indenting everything. As someone who often writes code that is unfortunately not very legible. Indenting would greatly improve the look and readability of my HTML code.

**Comment by superbuggy** [comment]
👍 nice! i would push back a little on #1 and say well-written HTML makes for well-written CSS. you don't have to do everything perfectly in one shot! I wish I had that ability.
