### ISSUE TITLE
Adam Whitehurst HTML Intro

### ISSUE THREAD

**Issue by nairul** [ga-wdi-lessons/html-intro#31]
1) For hexadecimal color codes, each pair of letters or numbers control how bright the red, blue, and green values should be (respectively). This helped solve my confusion about how hexadecimals are translated into colors! But I still prefer the rgba system...

2) Different browsers use different default style sheets!

3) Browserstack.com is a great site for testing compatibility.

**Comment by nayana487** [comment]
👍
