### ISSUE TITLE
HTML HW - Dan Lin

### ISSUE THREAD

**Issue by dlin2102** [ga-wdi-lessons/html-intro#32]
Things I've Learned
1. Abstraction is taking something super granular and turning it into something easier to grasp. 
2. The difference btw rich and plain text.
3. The importance of indenting.
4. The existence of HTML special characters and their basic formatting.
5. If you write HTML perfectly, you'll never need to touch it once you start writing CSS.

**Comment by AndyWhitley** [comment]
👍
