### ISSUE TITLE
HTML Intro Homework - Elena Santana

### ISSUE THREAD

**Issue by fanelenan7** [ga-wdi-lessons/html-intro#33]
&trade for trademark. That’s good to know, as well as &amp for &. That one is pretty funny...
Knew about `<q>` tag, but did not know about `<blockquote>` tag.

Compatibility and age of target user. Have not thought about it, though I should have. Makes sense that older folks, technophobes and ofc government would use IE. Because why would they not D:

**Comment by amaseda** [comment]
:+1:
