### ISSUE TITLE
Intro to HTML HW - Kevin Keller

### ISSUE THREAD

**Issue by kkeller93** [ga-wdi-lessons/html-intro#34]
Comfort: 5
Completeness: 5

One thing I learned when naming a function in HTML is that when deciding what to name the function. Give it a name according to it’s functionality not what it is going to look like. This will help you decipher on later on what it is that the function does.

The second thing I learned is that styles will change between browsers until you use normalize.css

The third thing that I learned is that there are three main properties in CSS selectors (selecting an element for modification), properties (things being modified), and values (properties being set)

**Comment by phantomhaircuts** [comment]
👍
