### ISSUE TITLE
Will Hawkins HTML Homework

### ISSUE THREAD

**Issue by hawkins-will** [ga-wdi-lessons/html-intro#7]
Three things I learned from this lesson:

The difference between Plain Text vs Rich Text (Rich Text has embedded code in it)

You should never name your HTML elements anything involving style. Use Semantic nomenclature

Special Characters are written with an Ampersand (&), an abbreviation, and a semicolon. These include: ampersands[&] (&amp;), angle brackets [<] (&lt;)/ [>] (&gt;), and many more.

**Comment by nayana487** [comment]
👍
