### ISSUE TITLE
Lisa Burr - Intro to HTML

### ISSUE THREAD

**Issue by laburr27** [ga-wdi-lessons/html-intro#8]
What I learned today:

1) Special characters all have the same form: an ampersand, followed by an abbreviation, followed by a semicolon.

2) Remember: If you write HTML perfectly, you'll never need to touch it once you start writing CSS.

3) Microsoft needs to get with the program and get over their need to conquer the interwebz.

**Comment by superbuggy** [comment]
👍 

re: number 2 my personal opinion is doing things efficiently and purposefully > perfection

much love on number 3
